/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inicioAdministrativo;

/**
 *
 * @author Lisett
 */
public class inicioAdministrativo extends javax.swing.JFrame {

    /**
     * Creates new form inicioAdministrativo
     */
    public inicioAdministrativo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        personalLabel = new javax.swing.JLabel();
        asistenciaLabel = new javax.swing.JLabel();
        salirLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 645));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(1280, 645));
        background.setRequestFocusEnabled(false);
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.jpg"))); // NOI18N
        logo.setText("jLabel1");
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 293, -1));

        personalLabel.setBackground(new java.awt.Color(255, 255, 255));
        personalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personalLabel.setText("PERSONAL");
        personalLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        personalLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        personalLabel.setMaximumSize(new java.awt.Dimension(198, 35));
        personalLabel.setMinimumSize(new java.awt.Dimension(198, 35));
        personalLabel.setName(""); // NOI18N
        personalLabel.setPreferredSize(new java.awt.Dimension(198, 35));
        background.add(personalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 323, -1, -1));

        asistenciaLabel.setBackground(new java.awt.Color(255, 255, 255));
        asistenciaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asistenciaLabel.setText("ASISTENCIA");
        asistenciaLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        asistenciaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asistenciaLabel.setMaximumSize(new java.awt.Dimension(198, 35));
        asistenciaLabel.setMinimumSize(new java.awt.Dimension(198, 35));
        asistenciaLabel.setName(""); // NOI18N
        asistenciaLabel.setPreferredSize(new java.awt.Dimension(198, 35));
        background.add(asistenciaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 371, -1, -1));

        salirLabel.setBackground(new java.awt.Color(255, 255, 255));
        salirLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salirLabel.setText("SALIR");
        salirLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        salirLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirLabel.setMaximumSize(new java.awt.Dimension(198, 35));
        salirLabel.setMinimumSize(new java.awt.Dimension(198, 35));
        salirLabel.setName(""); // NOI18N
        salirLabel.setPreferredSize(new java.awt.Dimension(198, 35));
        background.add(salirLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 419, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicioAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicioAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicioAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicioAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicioAdministrativo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asistenciaLabel;
    private javax.swing.JPanel background;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel personalLabel;
    private javax.swing.JLabel salirLabel;
    // End of variables declaration//GEN-END:variables
}
