/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lector;

/**
 *
 * @author Juan Martín
 */
public class Lector extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Asistencia
     */
    public Lector() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundLector = new javax.swing.JPanel();
        botonRegresar_Lector = new javax.swing.JButton();
        lectorAsistenciaTitle_Lector = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        dniBuscadorLabel_Lector = new javax.swing.JLabel();
        dniBuscadorTxtField_Lector = new javax.swing.JTextField();
        datosPersonalesLabel_Lector = new javax.swing.JLabel();
        nombresLabel_Lector = new javax.swing.JLabel();
        nombresTxtField_Lector = new javax.swing.JTextField();
        apePaternoLabel_Lector = new javax.swing.JLabel();
        apePaternoTxtField_Lector = new javax.swing.JTextField();
        apeMaternoLabel_Lector = new javax.swing.JLabel();
        apeMaternoTxtField_Lector = new javax.swing.JTextField();
        turnoLabel_Lector = new javax.swing.JLabel();
        turnoTxtField_Lector = new javax.swing.JTextField();
        horaActualLabel_Lector = new javax.swing.JLabel();
        horaActualTxtField_Lector = new javax.swing.JTextField();
        dniLabel_Lector = new javax.swing.JLabel();
        dniTxtField_Lector = new javax.swing.JTextField();
        fotoLabel_Lector = new javax.swing.JLabel();
        fotoTxtField_Lector = new javax.swing.JTextField();
        botonLeerPanel_Lector = new javax.swing.JPanel();
        leerLabel_Lector = new javax.swing.JLabel();
        botonRegistrarPanel_Lector = new javax.swing.JPanel();
        registrarLabel_Lector = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundLector.setBackground(new java.awt.Color(255, 255, 255));
        backgroundLector.setMinimumSize(new java.awt.Dimension(1280, 431));
        backgroundLector.setPreferredSize(new java.awt.Dimension(1280, 645));
        backgroundLector.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonRegresar_Lector.setBackground(new java.awt.Color(255, 255, 255));
        botonRegresar_Lector.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonRegresar_Lector.setForeground(new java.awt.Color(41, 98, 255));
        botonRegresar_Lector.setText("< REGRESAR");
        botonRegresar_Lector.setBorder(null);
        botonRegresar_Lector.setBorderPainted(false);
        botonRegresar_Lector.setContentAreaFilled(false);
        botonRegresar_Lector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresar_Lector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresar_LectorActionPerformed(evt);
            }
        });
        backgroundLector.add(botonRegresar_Lector, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 80, 30));

        lectorAsistenciaTitle_Lector.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lectorAsistenciaTitle_Lector.setText("LECTOR ASISTENCIA");
        backgroundLector.add(lectorAsistenciaTitle_Lector, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 47, -1, -1));

        jSeparator8.setBackground(new java.awt.Color(217, 217, 217));
        jSeparator8.setForeground(new java.awt.Color(217, 217, 217));
        jSeparator8.setPreferredSize(new java.awt.Dimension(1280, 0));
        backgroundLector.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 98, 1280, 20));

        dniBuscadorLabel_Lector.setText("DNI");
        backgroundLector.add(dniBuscadorLabel_Lector, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 156, -1, -1));

        dniBuscadorTxtField_Lector.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        dniBuscadorTxtField_Lector.setPreferredSize(new java.awt.Dimension(284, 35));
        backgroundLector.add(dniBuscadorTxtField_Lector, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 177, -1, -1));

        datosPersonalesLabel_Lector.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        datosPersonalesLabel_Lector.setText("DATOS PERSONALES");
        backgroundLector.add(datosPersonalesLabel_Lector, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 242, -1, -1));

        nombresLabel_Lector.setText("NOMBRES");
        backgroundLector.add(nombresLabel_Lector, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        nombresTxtField_Lector.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        nombresTxtField_Lector.setPreferredSize(new java.awt.Dimension(284, 35));
        nombresTxtField_Lector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresTxtField_LectorActionPerformed(evt);
            }
        });
        backgroundLector.add(nombresTxtField_Lector, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 270, -1));

        apePaternoLabel_Lector.setText("APELLIDO PATERNO");
        backgroundLector.add(apePaternoLabel_Lector, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));

        apePaternoTxtField_Lector.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        apePaternoTxtField_Lector.setPreferredSize(new java.awt.Dimension(284, 35));
        backgroundLector.add(apePaternoTxtField_Lector, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 200, -1));

        apeMaternoLabel_Lector.setText("APELLIDO MATERNO");
        backgroundLector.add(apeMaternoLabel_Lector, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 120, -1));

        apeMaternoTxtField_Lector.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        apeMaternoTxtField_Lector.setPreferredSize(new java.awt.Dimension(284, 35));
        backgroundLector.add(apeMaternoTxtField_Lector, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 180, -1));

        turnoLabel_Lector.setText("TURNO");
        backgroundLector.add(turnoLabel_Lector, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 346, -1, -1));

        turnoTxtField_Lector.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        turnoTxtField_Lector.setPreferredSize(new java.awt.Dimension(284, 35));
        backgroundLector.add(turnoTxtField_Lector, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 270, -1));

        horaActualLabel_Lector.setText("HORA ACTUAL");
        backgroundLector.add(horaActualLabel_Lector, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 110, -1));

        horaActualTxtField_Lector.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        horaActualTxtField_Lector.setPreferredSize(new java.awt.Dimension(284, 35));
        backgroundLector.add(horaActualTxtField_Lector, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 200, -1));

        dniLabel_Lector.setText("DNI");
        backgroundLector.add(dniLabel_Lector, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, -1, -1));

        dniTxtField_Lector.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        dniTxtField_Lector.setPreferredSize(new java.awt.Dimension(284, 35));
        backgroundLector.add(dniTxtField_Lector, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 180, -1));

        fotoLabel_Lector.setText("FOTO");
        backgroundLector.add(fotoLabel_Lector, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 280, -1, -1));

        fotoTxtField_Lector.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        fotoTxtField_Lector.setPreferredSize(new java.awt.Dimension(284, 35));
        backgroundLector.add(fotoTxtField_Lector, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 300, 110, 120));

        botonLeerPanel_Lector.setBackground(new java.awt.Color(199, 247, 247));
        botonLeerPanel_Lector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        leerLabel_Lector.setFont(new java.awt.Font("Inter SemiBold", 0, 14)); // NOI18N
        leerLabel_Lector.setText("LEER");

        javax.swing.GroupLayout botonLeerPanel_LectorLayout = new javax.swing.GroupLayout(botonLeerPanel_Lector);
        botonLeerPanel_Lector.setLayout(botonLeerPanel_LectorLayout);
        botonLeerPanel_LectorLayout.setHorizontalGroup(
            botonLeerPanel_LectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonLeerPanel_LectorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(leerLabel_Lector)
                .addContainerGap())
        );
        botonLeerPanel_LectorLayout.setVerticalGroup(
            botonLeerPanel_LectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonLeerPanel_LectorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(leerLabel_Lector)
                .addContainerGap())
        );

        backgroundLector.add(botonLeerPanel_Lector, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        botonRegistrarPanel_Lector.setBackground(new java.awt.Color(199, 247, 247));
        botonRegistrarPanel_Lector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        registrarLabel_Lector.setFont(new java.awt.Font("Inter SemiBold", 0, 14)); // NOI18N
        registrarLabel_Lector.setText("REGISTRAR");

        javax.swing.GroupLayout botonRegistrarPanel_LectorLayout = new javax.swing.GroupLayout(botonRegistrarPanel_Lector);
        botonRegistrarPanel_Lector.setLayout(botonRegistrarPanel_LectorLayout);
        botonRegistrarPanel_LectorLayout.setHorizontalGroup(
            botonRegistrarPanel_LectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonRegistrarPanel_LectorLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(registrarLabel_Lector)
                .addGap(40, 40, 40))
        );
        botonRegistrarPanel_LectorLayout.setVerticalGroup(
            botonRegistrarPanel_LectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonRegistrarPanel_LectorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registrarLabel_Lector)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backgroundLector.add(botonRegistrarPanel_Lector, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, -1, -1));

        getContentPane().add(backgroundLector, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 1300, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombresTxtField_LectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresTxtField_LectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresTxtField_LectorActionPerformed

    private void botonRegresar_LectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresar_LectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresar_LectorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apeMaternoLabel_Lector;
    private javax.swing.JTextField apeMaternoTxtField_Lector;
    private javax.swing.JLabel apePaternoLabel_Lector;
    private javax.swing.JTextField apePaternoTxtField_Lector;
    private javax.swing.JPanel backgroundLector;
    private javax.swing.JPanel botonLeerPanel_Lector;
    private javax.swing.JPanel botonRegistrarPanel_Lector;
    private javax.swing.JButton botonRegresar_Lector;
    private javax.swing.JLabel datosPersonalesLabel_Lector;
    private javax.swing.JLabel dniBuscadorLabel_Lector;
    private javax.swing.JTextField dniBuscadorTxtField_Lector;
    private javax.swing.JLabel dniLabel_Lector;
    private javax.swing.JTextField dniTxtField_Lector;
    private javax.swing.JLabel fotoLabel_Lector;
    private javax.swing.JTextField fotoTxtField_Lector;
    private javax.swing.JLabel horaActualLabel_Lector;
    private javax.swing.JTextField horaActualTxtField_Lector;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lectorAsistenciaTitle_Lector;
    private javax.swing.JLabel leerLabel_Lector;
    private javax.swing.JLabel nombresLabel_Lector;
    private javax.swing.JTextField nombresTxtField_Lector;
    private javax.swing.JLabel registrarLabel_Lector;
    private javax.swing.JLabel turnoLabel_Lector;
    private javax.swing.JTextField turnoTxtField_Lector;
    // End of variables declaration//GEN-END:variables
}
