/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InicioSesion;

/**
 *
 * @author Lisett
 */
public class inicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form inicioSesion
     */
    public inicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        userTxtf = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        contraLabel = new javax.swing.JLabel();
        contraTxt = new javax.swing.JPasswordField();
        logBtn = new javax.swing.JPanel();
        logBtnTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 645));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(1280, 645));
        background.setRequestFocusEnabled(false);
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.jpg"))); // NOI18N
        logo.setText("jLabel1");
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 132, 303, -1));

        userLabel.setText("Usuario");
        userLabel.setMaximumSize(new java.awt.Dimension(137, 16));
        userLabel.setPreferredSize(new java.awt.Dimension(137, 16));
        background.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 281, -1, -1));

        userTxtf.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        userTxtf.setPreferredSize(new java.awt.Dimension(284, 35));
        userTxtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtfActionPerformed(evt);
            }
        });
        background.add(userTxtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 302, -1, -1));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        contraLabel.setText("Contraseña");
        contraLabel.setPreferredSize(new java.awt.Dimension(137, 16));
        background.add(contraLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 360, -1, -1));

        contraTxt.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        contraTxt.setPreferredSize(new java.awt.Dimension(284, 35));
        background.add(contraTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 381, -1, -1));

        logBtn.setBackground(new java.awt.Color(199, 247, 247));
        logBtn.setPreferredSize(new java.awt.Dimension(284, 35));

        logBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logBtnTxt.setText("INGRESAR");
        logBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logBtnTxt.setPreferredSize(new java.awt.Dimension(137, 16));

        javax.swing.GroupLayout logBtnLayout = new javax.swing.GroupLayout(logBtn);
        logBtn.setLayout(logBtnLayout);
        logBtnLayout.setHorizontalGroup(
            logBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
        );
        logBtnLayout.setVerticalGroup(
            logBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        background.add(logBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 446, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(802, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTxtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel contraLabel;
    private javax.swing.JPasswordField contraTxt;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel logBtn;
    private javax.swing.JLabel logBtnTxt;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userTxtf;
    // End of variables declaration//GEN-END:variables
}
