/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Asistencia;

/**
 *
 * @author HP
 */
public class Asistencia extends javax.swing.JFrame {

    /**
     * Creates new form Asistencia
     */
    public Asistencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundAsistencia = new javax.swing.JPanel();
        asistenciaTitle_Asistencia = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        botonRegresar_Asistencia = new javax.swing.JButton();
        dniBuscadorLabel_Asistencia = new javax.swing.JLabel();
        dniBuscadorTxtField_Asistencia = new javax.swing.JTextField();
        botonBuscarPanel_Asistencia = new javax.swing.JPanel();
        buscarLabel_Asistencia = new javax.swing.JLabel();
        susAsistenciasLabel_Asistencia = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        susAsistenciasTable_Asistencia = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundAsistencia.setBackground(new java.awt.Color(255, 255, 255));
        backgroundAsistencia.setMinimumSize(new java.awt.Dimension(1280, 431));
        backgroundAsistencia.setPreferredSize(new java.awt.Dimension(1280, 645));
        backgroundAsistencia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        asistenciaTitle_Asistencia.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        asistenciaTitle_Asistencia.setText("ASISTENCIA");
        backgroundAsistencia.add(asistenciaTitle_Asistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 47, -1, -1));

        jSeparator8.setBackground(new java.awt.Color(217, 217, 217));
        jSeparator8.setForeground(new java.awt.Color(217, 217, 217));
        jSeparator8.setPreferredSize(new java.awt.Dimension(1280, 0));
        backgroundAsistencia.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 98, 1280, 20));

        botonRegresar_Asistencia.setBackground(new java.awt.Color(255, 255, 255));
        botonRegresar_Asistencia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonRegresar_Asistencia.setForeground(new java.awt.Color(41, 98, 255));
        botonRegresar_Asistencia.setText("< REGRESAR");
        botonRegresar_Asistencia.setBorder(null);
        botonRegresar_Asistencia.setBorderPainted(false);
        botonRegresar_Asistencia.setContentAreaFilled(false);
        botonRegresar_Asistencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresar_Asistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresar_AsistenciaActionPerformed(evt);
            }
        });
        backgroundAsistencia.add(botonRegresar_Asistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 80, 30));

        dniBuscadorLabel_Asistencia.setText("DNI");
        backgroundAsistencia.add(dniBuscadorLabel_Asistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 156, -1, -1));

        dniBuscadorTxtField_Asistencia.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        dniBuscadorTxtField_Asistencia.setPreferredSize(new java.awt.Dimension(284, 35));
        backgroundAsistencia.add(dniBuscadorTxtField_Asistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 177, -1, -1));

        botonBuscarPanel_Asistencia.setBackground(new java.awt.Color(199, 247, 247));
        botonBuscarPanel_Asistencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buscarLabel_Asistencia.setFont(new java.awt.Font("Inter SemiBold", 0, 14)); // NOI18N
        buscarLabel_Asistencia.setText("BUSCAR");

        javax.swing.GroupLayout botonBuscarPanel_AsistenciaLayout = new javax.swing.GroupLayout(botonBuscarPanel_Asistencia);
        botonBuscarPanel_Asistencia.setLayout(botonBuscarPanel_AsistenciaLayout);
        botonBuscarPanel_AsistenciaLayout.setHorizontalGroup(
            botonBuscarPanel_AsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonBuscarPanel_AsistenciaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buscarLabel_Asistencia)
                .addContainerGap())
        );
        botonBuscarPanel_AsistenciaLayout.setVerticalGroup(
            botonBuscarPanel_AsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonBuscarPanel_AsistenciaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buscarLabel_Asistencia)
                .addContainerGap())
        );

        backgroundAsistencia.add(botonBuscarPanel_Asistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        susAsistenciasLabel_Asistencia.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        susAsistenciasLabel_Asistencia.setText("SUS ASISTENCIAS");
        backgroundAsistencia.add(susAsistenciasLabel_Asistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 242, -1, -1));

        susAsistenciasTable_Asistencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRES", "APELLIDO PATERNO", "APELLIDO MATERNO", "DNI", "ESPECIALIDAD", "TURNO", "HORA LLEGADA", "HORA SALIDA", "TARDANZA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        susAsistenciasTable_Asistencia.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(susAsistenciasTable_Asistencia);
        if (susAsistenciasTable_Asistencia.getColumnModel().getColumnCount() > 0) {
            susAsistenciasTable_Asistencia.getColumnModel().getColumn(0).setResizable(false);
            susAsistenciasTable_Asistencia.getColumnModel().getColumn(1).setResizable(false);
            susAsistenciasTable_Asistencia.getColumnModel().getColumn(2).setResizable(false);
            susAsistenciasTable_Asistencia.getColumnModel().getColumn(3).setResizable(false);
            susAsistenciasTable_Asistencia.getColumnModel().getColumn(4).setResizable(false);
            susAsistenciasTable_Asistencia.getColumnModel().getColumn(5).setResizable(false);
            susAsistenciasTable_Asistencia.getColumnModel().getColumn(6).setResizable(false);
            susAsistenciasTable_Asistencia.getColumnModel().getColumn(7).setResizable(false);
            susAsistenciasTable_Asistencia.getColumnModel().getColumn(8).setResizable(false);
        }

        backgroundAsistencia.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 1060, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(backgroundAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(backgroundAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresar_AsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresar_AsistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresar_AsistenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asistencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asistenciaTitle_Asistencia;
    private javax.swing.JPanel backgroundAsistencia;
    private javax.swing.JPanel botonBuscarPanel_Asistencia;
    private javax.swing.JButton botonRegresar_Asistencia;
    private javax.swing.JLabel buscarLabel_Asistencia;
    private javax.swing.JLabel dniBuscadorLabel_Asistencia;
    private javax.swing.JTextField dniBuscadorTxtField_Asistencia;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel susAsistenciasLabel_Asistencia;
    private javax.swing.JTable susAsistenciasTable_Asistencia;
    // End of variables declaration//GEN-END:variables
}
