/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package personal;

/**
 *
 * @author Lisett
 */
public class personal extends javax.swing.JFrame {

    /**
     * Creates new form personal
     */
    public personal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        background = new javax.swing.JPanel();
        personalTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        dniBuscador = new javax.swing.JLabel();
        dniTxt = new javax.swing.JTextField();
        datosPersonalesLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        apePaternoLabel = new javax.swing.JLabel();
        apeMaternoLabel = new javax.swing.JLabel();
        especialidadLabel = new javax.swing.JLabel();
        dniLabel = new javax.swing.JLabel();
        nacimientoLabel = new javax.swing.JLabel();
        sexLabel = new javax.swing.JLabel();
        turnoLabel = new javax.swing.JLabel();
        telefonoLabel = new javax.swing.JLabel();
        fotoLabel = new javax.swing.JLabel();
        listaPersonalLabel = new javax.swing.JLabel();
        dniTxt1 = new javax.swing.JTextField();
        dniTxt2 = new javax.swing.JTextField();
        dniTxt3 = new javax.swing.JTextField();
        dniTxt4 = new javax.swing.JTextField();
        dniTxt5 = new javax.swing.JTextField();
        dniTxt6 = new javax.swing.JTextField();
        dniTxt7 = new javax.swing.JTextField();
        dniTxt8 = new javax.swing.JTextField();
        dniTxt9 = new javax.swing.JTextField();
        dniTxt10 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setMinimumSize(new java.awt.Dimension(1280, 431));
        background.setPreferredSize(new java.awt.Dimension(1280, 645));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        personalTitle.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        personalTitle.setText("PERSONAL");
        background.add(personalTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 47, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(217, 217, 217));
        jSeparator1.setForeground(new java.awt.Color(217, 217, 217));
        jSeparator1.setPreferredSize(new java.awt.Dimension(1280, 0));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 98, 1280, 30));

        dniBuscador.setText("DNI");
        background.add(dniBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 156, -1, -1));

        dniTxt.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        dniTxt.setPreferredSize(new java.awt.Dimension(284, 35));
        background.add(dniTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 180, -1));

        datosPersonalesLabel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        datosPersonalesLabel.setText("DATOS PERSONALES");
        background.add(datosPersonalesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 242, -1, -1));

        nombreLabel.setText("NOMBRES");
        background.add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        apePaternoLabel.setText("APELLIDO PATERNO");
        background.add(apePaternoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));

        apeMaternoLabel.setText("APELLIDO MATERNO");
        background.add(apeMaternoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 120, -1));

        especialidadLabel.setText("ESPECIALIDAD");
        background.add(especialidadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 280, -1, -1));

        dniLabel.setText("DNI");
        background.add(dniLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 346, -1, -1));

        nacimientoLabel.setText("FECHA DE NACIMIENTO");
        background.add(nacimientoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 150, -1));

        sexLabel.setText("SEXO");
        background.add(sexLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, -1, -1));

        turnoLabel.setText("TURNO");
        background.add(turnoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 350, -1, -1));

        telefonoLabel.setText("TELÉFONO");
        background.add(telefonoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, -1, -1));

        fotoLabel.setText("FOTO");
        background.add(fotoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 270, -1, -1));

        listaPersonalLabel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        listaPersonalLabel.setText("LISTA DE PERSONAL");
        background.add(listaPersonalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));

        dniTxt1.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        dniTxt1.setPreferredSize(new java.awt.Dimension(284, 35));
        background.add(dniTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 177, -1, -1));

        dniTxt2.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        dniTxt2.setPreferredSize(new java.awt.Dimension(284, 35));
        background.add(dniTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 370, 160, -1));

        dniTxt3.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        dniTxt3.setPreferredSize(new java.awt.Dimension(284, 35));
        background.add(dniTxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 300, 160, -1));

        dniTxt4.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        dniTxt4.setPreferredSize(new java.awt.Dimension(284, 35));
        background.add(dniTxt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 200, -1));

        dniTxt5.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        dniTxt5.setPreferredSize(new java.awt.Dimension(284, 35));
        background.add(dniTxt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 270, -1));

        dniTxt6.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        dniTxt6.setPreferredSize(new java.awt.Dimension(284, 35));
        background.add(dniTxt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, 90, -1));

        dniTxt7.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        dniTxt7.setPreferredSize(new java.awt.Dimension(284, 35));
        background.add(dniTxt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 180, -1));

        dniTxt8.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        dniTxt8.setPreferredSize(new java.awt.Dimension(284, 35));
        background.add(dniTxt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 190, -1));

        dniTxt9.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        dniTxt9.setPreferredSize(new java.awt.Dimension(284, 35));
        background.add(dniTxt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 290, 110, 120));

        dniTxt10.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        dniTxt10.setPreferredSize(new java.awt.Dimension(284, 35));
        background.add(dniTxt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 170, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRES", "APELLIDO PATERNO", "APELLIDO MATERNO", "DNI", "ESPECIALIDAD", "TURNO", "GENERO", "F. NACIMIENTO", "CELULAR", "FOTO"
            }
        ));
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        background.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 1060, 180));

        jPanel2.setBackground(new java.awt.Color(199, 247, 247));

        jLabel2.setFont(new java.awt.Font("Inter SemiBold", 0, 14)); // NOI18N
        jLabel2.setText("BUSCAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        jPanel5.setBackground(new java.awt.Color(199, 247, 247));

        jLabel3.setFont(new java.awt.Font("Inter SemiBold", 0, 14)); // NOI18N
        jLabel3.setText("REGISTRAR");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(40, 40, 40))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, -1, -1));

        jPanel4.setBackground(new java.awt.Color(199, 247, 247));

        jLabel4.setFont(new java.awt.Font("Inter SemiBold", 0, 14)); // NOI18N
        jLabel4.setText("ACTUALIZAR");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, -1, -1));

        jPanel3.setBackground(new java.awt.Color(199, 247, 247));

        jLabel1.setFont(new java.awt.Font("Inter SemiBold", 0, 14)); // NOI18N
        jLabel1.setText("LIMPIAR");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        background.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new personal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apeMaternoLabel;
    private javax.swing.JLabel apePaternoLabel;
    private javax.swing.JPanel background;
    private javax.swing.JLabel datosPersonalesLabel;
    private javax.swing.JLabel dniBuscador;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JTextField dniTxt;
    private javax.swing.JTextField dniTxt1;
    private javax.swing.JTextField dniTxt10;
    private javax.swing.JTextField dniTxt2;
    private javax.swing.JTextField dniTxt3;
    private javax.swing.JTextField dniTxt4;
    private javax.swing.JTextField dniTxt5;
    private javax.swing.JTextField dniTxt6;
    private javax.swing.JTextField dniTxt7;
    private javax.swing.JTextField dniTxt8;
    private javax.swing.JTextField dniTxt9;
    private javax.swing.JLabel especialidadLabel;
    private javax.swing.JLabel fotoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel listaPersonalLabel;
    private javax.swing.JLabel nacimientoLabel;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel personalTitle;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JLabel telefonoLabel;
    private javax.swing.JLabel turnoLabel;
    // End of variables declaration//GEN-END:variables
}
